language: node_js
node_js:
  - 16.13.0

cache: yarn

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "ap-northeast-2"
  app: "ci-cd-test"
  env: "$EB_ENV"
  bucket_name: "$EB_BUCKET_NAME"
